[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo", "php83Extensions.pgsql", "php83Extensions.pdo_pgsql", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.redis", "php83Extensions.pcntl", "php83Extensions.curl", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.dom", "php83Extensions.tokenizer", "php83Extensions.fileinfo", "ffmpeg"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan queue:work --tries=3 --timeout=600 --memory=512"
