[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Extensions.pdo", "php84Extensions.pgsql", "php84Extensions.pdo_pgsql", "php84Extensions.zip", "php84Extensions.gd", "php84Extensions.redis", "php84Extensions.pcntl", "php84Extensions.curl", "php84Extensions.mbstring", "php84Extensions.xml", "php84Extensions.dom", "php84Extensions.tokenizer", "php84Extensions.fileinfo", "ffmpeg"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan queue:work --tries=3 --timeout=600 --memory=512"
